### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by ghost** [tributemedia/testimonials#2]
Error that occurs on install. I had to set my Drupal environment logging to full to see this error, so this is probably normally suppressed. No functionality affected so far as I can tell, but should probably still be taken care of
![TestimonialInstallWarning](https://user-images.githubusercontent.com/66531458/136294919-ed46e5a3-c485-45aa-ba48-689ea0b31a04.PNG)
.

**Comment by skenley** [comment]
Not able to duplicate.
